name = "TestEnv"
uuid = "1e6cf692-eddd-4d53-88a5-2d735e33781b"
version = "2.0.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
ChainRulesCore = "=1.0.2"
MCMCDiagnosticTools = "=0.1.0"
YAXArrays = "0.1.3"
julia = "1"

[extras]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
MCMCDiagnosticTools = "be115224-59cd-429b-ad48-344e309966f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"

[targets]
test = ["ChainRulesCore", "MCMCDiagnosticTools", "Test", "YAXArrays"]
